---
proxmox_vm_storage: "vm_local"
proxmox_iso_storage: "iso_local"

dotfiles_repo_local_destination: "{{ ansible_user_dir }}/src/dotfiles"
dotfiles_repo: "https://github.com/fishd72/Dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: false

dotfiles_home: "~"

dotfiles_directories:
  - .config/nvim/
  - .config/tmux/
  - .config/vifm/colors/
  - .config/lxterminal/
  - .vim/colors/
  - .zsh/

dotfiles_files:
  - .aliases
  - .config/lxterminal/lxterminal.conf
  - .config/vifm/vifmrc
  - .config/vifm/colors/palenight.vifm
  - .dir_colors
  - .gitconfig
  - .gitconfig-linux
  - .gitconfig-macos
  - .gitconfig-personal
  - .gitconfig-corporate
  - .gitignore
  - .hushlogin
  - .nanorc
  - .vim/colors/nord.vim
  - .vimrc
  - .zprofile
  - .zshrc

zsh_plugins:
  - https://github.com/agkozak/agkozak-zsh-prompt
  - https://github.com/zsh-users/zsh-autosuggestions
  - https://github.com/zsh-users/zsh-history-substring-search
  - https://github.com/zsh-users/zsh-syntax-highlighting

basic_packages: [ 'wget', 'curl', 'zsh', 'git', 'vifm', 'nano', 'tmux', 'lolcat', 'fortune-mod' ]

neovim_download: https://github.com/neovim/neovim/releases/download/v0.9.1/nvim.appimage

git_repos:
  - https://github.com/agkozak/agkozak-zsh-prompt
  - https://github.com/zsh-users/zsh-syntax-highlighting
  - https://github.com/zsh-users/zsh-history-substring-search
  - https://github.com/zsh-users/zsh-autosuggestions

# Code to work out correct Debian repo Architectures.
# Use {{ apt_repo_arch_type[ansible_architecture] }} instead of [arch=amd64]

apt_repo_arch_type:
  x86_64: amd64
  ia64: amd64
  aarch64: arm64
  armv6l: armel
  armv7l: armhf

# Code to work out correct Linux Mint repositories.
# Use {{ apt_repo_mint_fix[ansible_distribution_release] }} instead of [ansible_lsb_codename]

apt_repo_mint_fix:
  una: focal
  uma: focal
  ulyssa: focal
  ulyana: focal
  tricia: bionic
  tina: bionic
  tessa: bionic
  tara: bionic
  elsie: bullseye
  debbie: buster
  focal: focal
  bionic: bionic
  bullseye: bullseye
  buster: buster
  bookworm: bookworm
