---
- hosts: all

  become: true

  vars_files:
    - passwd.yml

  tasks:

  # Create Portainer Volume
  # --
  #
  - name: Create new Volume
    community.docker.docker_volume:
      name: portainer-data

  # Deploy Portainer
  # --
  #
  - name: Deploy Portainer
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      restart_policy: always

  # Deploy Watchtower
  # --
  #
  - name: Deploy Watchtower
    community.docker.docker_container:
      name: watchtower
      image: "containrrr/watchtower"
      command: --schedule "0 0 4 * * *"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart_policy: always