all:
  children:
    local:
      children:
        raspberrypi:
          hosts:
            pibot:
              ansible_host: 192.168.178.207
            tinyca:
        desktops:
          hosts:
        wsl:
          hosts:
        devops:
          hosts:
    remote:
      children:
        azure:
          hosts:
        aws:
          hosts: