all:
  children:
    local:
      children:
        desktops:
          hosts:
        wsl:
          hosts:
            localhost:
        devops:
          children:
            wsl:
            devbox:
    remote:
      children:
        azure:
          hosts:
            devbox:
        aws:
          hosts: