all:
  children:
    local:
      children:
        physical:
          children:
            servers:
              children:
                raspberrypi:
                  hosts:
                    pibot:
                      ansible_host: "pibot.local.fishd.uk"
                proxmox:
                  hosts:
                    freya:
                      ansible_host: "freya.local.fishd.uk"
                synology:
                  hosts:
                    synobot:
            clients:
              children:
                desktops:
                  hosts:
                    archimedes:
                    mintbox:
                macs:
                  hosts:
                    leviathan:
                      ansible_host: mintvert.local.fishd.uk
                laptops:
                  hosts:
                    framework:
        virtual:
          children:
            containers:
              hosts:
                pihole:
                  ansible_host: pihole.local.fishd.uk
            vms:
              hosts:
                ansible:
                  ansible_host: ansible.local.fishd.uk
                docker:
                  ansible_host: docker.local.fishd.uk
                valheim:
                  ansible_host: valheim.local.fishd.uk
    remote:
      children:
        azure:
          hosts:
        aws:
          hosts:
        hetzner:
          hosts: