---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - gpg-agent
    state: present
    update_cache: yes

- name: Add the Signal GPG Key
  ansible.builtin.apt_key:
    url: "{{ signal_gpg_path }}"
    keyring: "{{ signal_gpg_key }}"

- name: Add Signal Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ signal_gpg_key }}] {{ signal_repo_path }}
    filename: signal
    state: present

- name: Ensure Signal is installed.
  ansible.builtin.apt:
    name: "{{ signal_package_name }}"
    state: "{{ signal_package_state }}"
    update_cache: yes