---
- name: Verify that the user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ item }}"
  tags:
    - zsh
    - shell
    - user

- name: Ensure zsh is the default shell
  ansible.builtin.user:
    name: "{{ item }}"
    shell: "{{ install_zsh_executable }}"
  tags:
    - zsh
    - shell
    - user
