# handlers file for fqdn
---
- name: Restart hostname
  ansible.builtin.service:
    name: "hostname{{ '.sh' if (ansible_distribution_release == 'wheezy') else '' }}"
    state: restarted
  when: >
    ansible_os_family != 'RedHat'
    and ansible_service_mgr != 'systemd'

- name: Restart systemd-logind
  ansible.builtin.service:
    name: systemd-logind
    state: restarted
  when: >
    ansible_os_family != 'RedHat'
    and ansible_service_mgr == 'systemd'
