- name: Add mesa repository
  apt_repository:
    repo: "{{ mesa_repo_path }}"
    state: present
    codename: "{{ apt_repo_mint_fix[ansible_distribution_release] }}"

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes