- name: extensions for vscode
  shell: code --install-extension {{ item }}
  register: vscode_result
  changed_when: "'was successfully installed' in vscode_result.stdout"
  with_items:
    - "{{ default_vscode_packages }}"

- name: Populate settings for VSCode on Linux
  template:
      dest: "{{ ansible_user_dir }}/.config/Code/User/settings.json"
      src: "{{ role_path }}/templates/vscode_settings.j2"
      force: yes 
  when: ansible_os_family != "Darwin"

- name: Populate settings for VSCode on macOS
  template:
      dest: "{{ ansible_user_dir }}/Library/Application\ Support/Code/User/settings.json"
      src: "{{ role_path }}/templates/vscode_settings.j2"
      force: yes 
  when: ansible_os_family == "Darwin"