---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - gpg-agent
    state: present
    update_cache: yes

- name: Add the Slack GPG Key
  ansible.builtin.apt_key:
    url: "{{ slack_gpg_path }}"
    keyring: "{{ slack_gpg_key }}"

- name: Add Slack Repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by={{ slack_gpg_key }}] {{ slack_repo_path }}
    filename: slack
    state: present

- name: Ensure Slack is installed.
  ansible.builtin.apt:
    name: "{{ slack_package_name }}"
    state: "{{ slack_package_state }}"
    update_cache: yes