---
vscode_setup_sf_font: true
default_vscode_packages:
  - bbenoist.vagrant
  - DavidAnson.vscode-markdownlint
  - esbenp.prettier-vscode
  - marcostazi.VS-code-vagrantfile
  - mrmlnc.vscode-duplicate
  - ms-python.python
  - redhat.ansible
  - arcticicestudio.nord-visual-studio-code