- name: "Perform a dist-upgrade"
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: "Check if a reboot is required"
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: "Remove useless packages from the cache"
  ansible.builtin.apt:
    autoclean: yes

- name: "Remove dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: yes

- name: "Reboot the server (if required)"
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists == true