---
- name: Secure SSH
  ansible.builtin.lineinfile:
    dest: "{{ config_sshd_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: /usr/sbin/sshd -T -f %s
  with_items:
    - { regexp: "^#Port 22", line: "Port 22" }
    - { regexp: "^#MaxAuthTries 6", line: "MaxAuthTries 3" }
    - { regexp: "^#MaxSessions 10", line: "MaxSessions 2" }
    - { regexp: "^#ClientAliveInterval 0", line: "ClientAliveInterval 15" }
    - { regexp: "^#ClientAliveCountMax 3", line: "ClientAliveCountMax 3" }
    - { regexp: "^#PasswordAuthentication ", line: "PasswordAuthentication no" }
    - { regexp: "^#PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "^#PermitEmptyPasswords", line: "PermitEmptyPasswords no" }
    - { regexp: "^X11Forwarding yes", line: "X11Forwarding no" }
    - { regexp: "^#LoginGraceTime", line: "LoginGraceTime 30" }
  notify: "Restart sshd"
