---
install_docker_repo_path: "https://download.docker.com/linux/{{ ansible_os_family | lower }} {{ apt_repo_mint_fix[ansible_distribution_release] }} stable"
install_docker_gpg_path: "https://download.docker.com/linux/{{ ansible_os_family | lower }}/gpg"
install_docker_gpg_key: /usr/share/keyrings/docker-ce-keyring.gpg
