---
- name: Configure Debian fqdn
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure Redhat fqdn
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Configure Linux fqdn
  ansible.builtin.include_tasks: linux.yml
  when: ansible_system in [ 'Linux' ]
